INSERT IGNORE INTO watch VALUES (10, 6);
INSERT IGNORE INTO watch VALUES (10, 9);
INSERT IGNORE INTO watch VALUES (13, 6);
INSERT IGNORE INTO watch VALUES (13, 9);
INSERT IGNORE INTO watch VALUES (9, 6);
INSERT IGNORE INTO watch VALUES (9, 9);